### ISSUE TITLE
Web Root setting not working

### ISSUE THREAD

**Issue by Programie** [zipleen/tvheadend-iphone-client#151]
Hi,

I'm running my Tvheadend server behind an Apache reverse proxy (mod_proxy) and therefore have changed the default web root.

There is an option in TvhClient to specify an alternative web root, but the setting does nothing.

I'm using TvhClient 2.7.0 (649) and Tvheadend 3.9.2497.

**Comment by zipleen** [comment]
Hi,

That option was added a long time ago and it was working, but I don't use it frequently so it could have broken for some weird reason..

The easiest way of me helping is getting access to the url, so I can debug what's happening. Can you contact me via email and give me some details on how I can access your tvheadend instance? tvhclient@gmail.com

**Comment by Programie** [comment]
Hi,

I think the easiest way for you to debug that would be to install Tvheadend and start it with the "--http_root" option. That should also work without any DVB hardware.

In my case I pass "/tvheadend" to it. And I've configured exactly the same path as the Web Root in TvhClient.

The execution of tvheadend could look like "tvheadend --http_root /tvheadend".

**Comment by zipleen** [comment]
![screen shot 2015-02-16 at 12 03 14](https://cloud.githubusercontent.com/assets/1225055/6211619/ef582c4e-b5d3-11e4-8a93-5bc5b5c3a13c.png)

I've ran tvheadend with the http_root, configured tvhclient with a wrong path and you can see the errors because of that. I then configured with the correct "/tvheadend" path and you can see the channels in the screenshot. It also shows the status, so everything seems to be working ok.

This only leaves you entering the wrong root in the tvhclient configuration, or your setup has something that I'm not anticipating - either way you need to check that in your end.

**Comment by zipleen** [comment]
Closing as this doesn't seem to be a bug in tvhclient. Reopen this with a specific use case where this fails so I can track it down!
