### ISSUE TITLE
 At TVHeadend Client on iPhone 6 "TVHeadend returned malformed JSON.. "

### ISSUE THREAD

**Issue by gianpycos** [zipleen/tvheadend-iphone-client#152]
Hi,
as I mentioned in the title, when I connect to tvheadend I get that error. I changed charset option but nothing changed.

EPG in the web interface works and also channels list on Xbmc works.

Any suggestion?

Thanks

**Comment by zipleen** [comment]
Hi,
As per the previous tickets, that error is always because of the charset. You need to double check if the streams have the correct charset selected.

Unfortunately I couldn't find a way to "clear up" a corrupted charset automatically. The JSON decoder in iOS seems to not like weird characters, otherwise it will just fail completely.

Some things you could check:
- you can set the charset per adapter, but double check if the charset is correct on the muxes
- make sure you don't have channels that have a different charset inside the mux 
- you could think your charset is correct but it's not, for example my networks are all ISO-8859-15

Xbmc uses HTSP and even if it has weird characters inside it can ignore/display them, like the web interface which just shows weird.

I can't replicate this in my tvheadend servers, so if you can't make this work the only thing I can help is having access to the server and checking if this is a real bug because of some new thing in tvheadend (highly unlikely though)

**Comment by gianpycos** [comment]
Hi,
thanks for you hints, I will try them hoping that avoid the problem. However, I noticed that sometime the APP loads all channel lists, and other times give the JSON error. 

Just to say that my server is on Raspberry, and charset is UTF-8. Moreover, I get a lot of unknown channels, may this depend on the wrong JSON?

Thanks

**Comment by zipleen** [comment]
Just a quick reminder, thinking that your charset is UTF-8 could be your deception. The charset is dependent on the mux that's sent by the satellite and has nothing to do with the charset of your environment. 
Make sure that your streams actually have UTF-8 encoded strings.

Channel list should always load or not ... While loading the channel list you could get that error because loading the channel list also loads a little bit of the EPG (consumes EPG entries up to 6 hours in the future if I'm not mistaken) - if there's no extended characters in those 6 hours you won't get the error!

**Comment by gianpycos** [comment]
On 11 Mar 2015, at 12:01, Luis Fernandes <notifications@github.com> wrote:
> 
> Just a quick reminder, thinking that your charset is UTF-8 could be your deception. The charset is dependent on the mux that's sent by the satellite and has nothing to do with the charset of your environment. Make sure that your streams actually have UTF-8 encoded strings
> 
At the moment I’m grabbing DVB-T italian mux. How can I check the stream encode charset on tvheadend?
> Channel list should always load or not ... While loading the channel list you could get that error because loading the channel list also loads a little bit of the EPG (consumes EPG entries up to 6 hours in the future if I'm not mistaken) - if there's no extended characters in those 6 hours you won't get the error!
> 
> 
Ok, I’ll verify this point, I’ve started yesterday evening the first service scan. Maybe it takes hours for the EPG, as you said.

**Comment by zipleen** [comment]
I have no idea how to find out the charset of a stream =)
But if it's italian, I would bet on ISO-8859-15 ! Maybe the guys on IRC freenode/#hts have some ideas on that one..

By the way, when you say "I look in the web interface and I see the epg correctly" you need to be looking for words that have é à É í ó ú ç and extended characters like these - they should be also broken on the web interface, you just don't notice them too much. If those are ok in the web interface, you should not have any more problems with TvhClient.

**Comment by gianpycos** [comment]
> On 11 Mar 2015, at 12:38, Luis Fernandes <notifications@github.com> wrote:
> 
> I have no idea how to find out the charset of a stream =)
> But if it's italian, I would bet on ISO-8859-15 ! Maybe the guys on IRC freenode/#hts have some ideas on that one..
> 
> 
Ok :)

> By the way, when you say "I look in the web interface and I see the epg correctly" you need to be looking for words that have é à É í ó ú ç and extended characters like these - they should be also broken on the web interface, you just don't notice them too much. If those are ok in the web interface, you should not have any more problems with TvhClient.
> 
> 
Thanks, I’ll check it out.

**Comment by zipleen** [comment]
If there's a bug that you can replicate, please re-open this ticket and add the steps to reproduce (or get a dump from tvheadend and attach it here - check https://github.com/zipleen/tvheadend-iphone-client/issues/127#issuecomment-30250725 for details )
