### ISSUE TITLE
Hd streaming

### ISSUE THREAD

**Issue by snoopy86** [zipleen/tvheadend-iphone-client#153]
Hi,

sd content works without a problem. When i want to play HD content it just shows still image and the sound is playing. What can i change?
Iphone 6, tvheadend 3.9.2345~gf5c8e4c

**Comment by zipleen** [comment]
I guess that you try to play content with the "Internal VLC" option ? If so, try with the VLC app and report back if it works ok (and which VLC version you used and any settings that you changed for it to work). 

The internal vlc option uses VLC and there's little I can do to make it work better than what the VLC app does, unless it's a configuration setting that I need to set.

For reference, on my ipad mini retina I can watch HD channels if they're in my local LAN. Watching through the internet is almost impossible because it crashes every 30 seconds.

**Comment by zipleen** [comment]
Closing because there isn't much I can do without having an actual iPhone 6 to test =)
My iPad Mini retina works ok though (and supposedly has a less performant CPU/GPU)
