### ISSUE TITLE
Use only HTSP dvr recording API - for separated user accounts

### ISSUE THREAD

**Issue by dreamcat4** [zipleen/tvheadend-iphone-client#154]
Relying on admin user right, or DVR web api means all recording are mixed up for different users. By switching to HTSP api it means separate accounts can co-exist properly.

ATM my accounts give 404 error because no admin / no web DVR. This is also something which might be generally improved with the tvheadend APIs. I am not sure!

:)

**Comment by zipleen** [comment]
That seems like a tvheadend issue - if you use the web interface you shall have the same issue as in tvhclient. 

I will not support HTSP because it's a total rewrite on tvheadend-ios-lib, HTSP will probably eventually disappear replaced by HTTP and there's little gain to have HTSP support - these small issue will need to be fixed for the web api anyway.

But if you have a spare few hours you can do another tvheadend-ios-lib using HTSP and plug it in tvheadend-iphone-client and it should work =)

**Comment by dreamcat4** [comment]
Hello again. Another good news:

This issue might be fixed today by perexg, in main tvheadend upstream project:

On master:

https://github.com/tvheadend/tvheadend/commit/4c9e009ce8b4e074d6f244ddc4f05ebaa3302dab
https://github.com/tvheadend/tvheadend/commit/a8ac26d7624751e8826acf41c98ddd81a9dd79e7

On `release/4.0` branch:

https://github.com/tvheadend/tvheadend/commit/abed8f3c687ca953d5a00e536fc791080c655ca4
