### ISSUE TITLE
Kodi 14.2 remote playback (tv and radio) does not work but current playback stops

### ISSUE THREAD

**Issue by x23piracy** [zipleen/tvheadend-iphone-client#156]
Hi,

it's not possible to start a tv or radio channel on a remote kodi system, playback of the tv or radio channel does not start but an already running playback stops.

Could this be fixed please?
Anyway Internal VLC usage is running fine.

Regards X23

**Comment by zipleen** [comment]
Hi, can you give me a little bit more details? What tvheadend and kodi version are you running ?

**Comment by x23piracy** [comment]
Hi,

sure what ever you need, like i said it Kodi 14.2 Helix (final) 2 Openelec Systems (5.0.8) and one Windows Kodi 14.2 under Windows. All the Systems have everything enabled thats needed for remote access:

http://i.imgur.com/cMuUkvy.png
http://i.imgur.com/vnrV5eE.png
http://i.imgur.com/5lIRFq6.png
http://i.imgur.com/3Q7b63u.png

If i start your app it recognizes all the running kodi system, so when i tap playback i can see the kodi systems in the menu, now when i tap one of them nothing happens.

How does your app deal with kodi? Are you using the old way or is it the json implementation?
Is it a problem when the webif has a password set?

TVHeadend is Version: 3.9.2765~g0294882


Regards X23

**Comment by zipleen** [comment]
I'm using the json implementation, which should not have changed : https://github.com/zipleen/tvheadend-ios-lib/blob/master/tvheadend-ios-lib/TVHPlayXbmc.m#L85

It's probably something to do with tvheadend htsp url not working anymore... You do have a more recent version of tvheadend than me, so I'll need to upgrade and test out any changes. 

The url I build is in https://github.com/zipleen/tvheadend-ios-lib/blob/master/tvheadend-ios-lib/TVHChannel.m#L137 and this could be the problem. I send the HTSP instead of the http url to kodi because it's faster to start and supports all the native tvheadend stuff, but that url could have changed - and if it did I'm stuck again because that url is used for old tvheadend versions to work =)

Supporting a lot of different versions in tvheadend is a real pain...

**Comment by x23piracy** [comment]
Hi,

this is how looks like in the app: http://i.imgur.com/jp1j62e.png
Ok are you willing to test this with a more recent version of tvh to fix this?


Regards X23

**Comment by zipleen** [comment]
yes of course, I'll try to do that tonight. If it's too complicated it will have to wait 1 more week because I'm not going to be available =)

**Comment by x23piracy** [comment]
ok fine maybe there is a way to implement a version detection to use the right urls?

**Comment by zipleen** [comment]
I'm sure I'll have to find out :p
It would be good if tvheadend changed api versions if things like this happened, but I don't think they changed anything. 

I'll have a look tonight.

**Comment by x23piracy** [comment]
This is maybe related to it? https://github.com/xbmc/xbmc/pull/6699

**Comment by x23piracy** [comment]
Hi zipleen,

i downloaded the ipa now and will test it in the next 1-2 hours, i get back to you.


Regards X23

**Comment by x23piracy** [comment]
Hi,

first test: does not work no reaction from one of the kodi systems.


Regards X23

**Comment by zipleen** [comment]
Hi again,
I've downloaded kodi 14.2 stable and it works ok, even with the htsp protocol. The HTSP protocol situation we discussed on irc will only occur in kodi 15.

This means there's something going on with your system, because it works flawlessly on all my kodi instances.
I've also upgraded to tvheadend 4.1 and it works perfectly.

Can you enable debug log in kodi and check what happens when you start a stream? maybe it has some more information there.

**Comment by x23piracy** [comment]
Hi,

did so but the confusing thing is there is nothing in the log: http://pastebin.com/HHhe3q7M
with your ipa i updated from the last 2.7.2 will this work? or should i uninstall before i install your test ipa?

**Comment by zipleen** [comment]
can we talk over irc? it's faster that way. 

You can install the ipa over the stable version, there's no issues with that.
Regarding your log, you should have something like this in your logs:
```
21:45:46 T:4681736192   DEBUG: webserver: request received for /jsonrpc
21:45:46 T:4681736192   DEBUG: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"player.open","params":{"item":{"file":"htsp:\/\/bananapi1:9982\/tags\/0\/658312231.ts"}}}
21:45:47 T:140735108809472   DEBUG: Loading settings for htsp://bananapi1:9982/tags/0/658312231.ts
```
 I can only see the request received, but there's nothing else. Try to enable JSON-RPC in the component-specific logging

**Comment by zipleen** [comment]
Ok, issue was tvhclient does not support user/pass in kodi :)
