### ISSUE TITLE
No more channel icons

### ISSUE THREAD

**Issue by mrblond18** [zipleen/tvheadend-iphone-client#161]
I used to have channel icons and group icons in TVHClient on my iPhone. However nowadays I do not get any channel and group icons anymore.

In TVHeadend I have entered my icons as:
https://jeroentje.raspberryip.com/TVLogos/fromghm/ned1.png

In Kodi they do show up. Maybe it has something to do with the httpS, I don't know...

Can you tell me what to do to get them back? Or do I need to supply more info?

**Comment by zipleen** [comment]
Hi, you're https server certificate is not signed / valid. That's why the images don't appear, get a valid certificate or install the root certificate that was used to sign the https certificate into your iOS device.

I would just get a valid certificate from startssl :)

**Comment by mrblond18** [comment]
Thanks for the quick reply!

Two things:
a friend of mine also has a TVH server, he is not using a https connection for his logo's, e.g.
http://ivowetters.no-ip.org/TVLogos/fromghm/ned1.png

When I add that server to my TVHClient app, still no logos appear...

Second: how do I add this certificate in iOS? I think I already did that. When I open
https://jeroentje.raspberryip.com/TVLogos/fromghm/ned1.png
in Safari, it just shows the logo without complaining about a not-valid certificate.

**Comment by zipleen** [comment]
That first url returns 404, so there's no image. Check if the url is publicly accessible or if there's any vhosts doing something they're not suppose to :p

In regards to the certificate, I'm not too sure that it will work because of some security features in iOS8 and how AFNetworking works. I don't have time to investigate this right now though...

Try using a non https version and if it works just get a valid https certificate (these guys https://www.startssl.com give them for free)

**Comment by mrblond18** [comment]
Thanks, I switched back to http... Solved!

Startssl does nog give the certificates for free for subdomains, so no use for me

**Comment by zipleen** [comment]
Ok great.
You can also use the icon cache in tvheadend - enable that option and tvheadend will fetch the icons for you and deliver them through your tvheadend server.
