### ISSUE TITLE
EPG not available

### ISSUE THREAD

**Issue by AT00230** [zipleen/tvheadend-iphone-client#164]
Hi, i'am using TvH 4.1-442~g824f46e and do not get any EPG information in your client.

I'm always get the message ,EPG not available' on all channels!

Client is on the latest version 2.7.5!

Is there a knowing issue?

Thanks & kind regards, Andreas

**Comment by holli73** [comment]
Same here since latest app update no epg anymore

**Comment by zipleen** [comment]
It seems tvheadend added get again 2 more api versions, 17 and 18. 

I can't keep up adding version numbers and releasing new versions as fast as changing a number in a file - the apple process takes at least one week to get an update online.

If you want to get the epg back, downgrade to a version from a week ago, or change in api.h the API level from 18 to 16 and you'll get it back. Either that or use a stable branch 4.0 - or you need to deal with the consequences of using bleeding edge versions.

The default api version for tvhclient is still 3.4 because there's a lot of people using that stable version. Eventually I'll change the default version to be 4.0 but until then if they keep adding version numbers, tvhclient will fail to work if not updated.

I'll send an updated version next week, expect that it will take at least 2 weeks for Apple to approve it.

**Comment by AT00230** [comment]
Ok, thanks for your work!

**Comment by m4rcs** [comment]
Where are the API versions documented? I didn't find it.

**Comment by zipleen** [comment]
In tvheadend documentation? I have no idea =)
In the source you can find the api version number in https://github.com/tvheadend/tvheadend/blob/master/src/api.h

If you're searching for a fix for the EPG, I've actually found the real bug why this is happening but it's still waiting to be reviewed by apple.

I was actually wrong with my previous comment, 1 year and a half ago I've already about this and tvhclient should support forward facing versions correctly, however there was a bug in the EPG code that prevented this from happening, hence why the EPG was the only thing breaking.
