### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by kmengvik** [zipleen/tvheadend-iphone-client#171]
![image](https://cloud.githubusercontent.com/assets/16176305/13718190/02a1ef50-e7e8-11e5-8a38-7da74e9f7b7a.png)

**Comment by zipleen** [comment]
Hi, a little bit more details are necessary, that error is normal when the connection to tvheadend is not available =)

**Comment by kmengvik** [comment]
Thank you for super swift reply. Unreal fast!!.

I've entered exactly the same values and credentials in your app, as I did in tvheadend addon in kodi on apple TV and on Windows computer. Only your app has a problem with it. What may be the issue?

Kai

Sendt fra min iPad

**Comment by zipleen** [comment]
The easiest way is for you to open Safari and input the "Address:Port" (that you've inputed in tvhclient) in the address bar and see if you can access it from safari.  

Bear in mind that Kodi does not use the same protocol as tvhclient: kodi uses HTSP and tvhclient uses exclusively the HTTP port (which you can access from safari).

**Comment by kmengvik** [comment]
Sendt fra min iPad

**Comment by kmengvik** [comment]
Yes, did reach it from Safari.

Kai

Sendt fra min iPad

**Comment by zipleen** [comment]
Then you need to double check the parameters in tvhclient - username and password.

You're getting the 401 error which can mean wrong username / password or you need to put a webroot. Check all those values again.

**Comment by kmengvik** [comment]
Hi again. Everything was set up correctly. The issue turned out to be that I had to get my username granted access to the web interface. The administrator arranged this, and now the TV channels are available on my iPad. However a new issue has rosen. Probably a new thread should be created for this. This new issue is that when airplay button is hit in the internal VLC player, then the stream gets strangled. Also the video does not display on the apple TV. The ATV recognizes that a request has been sent by announcing the title of the TV show in the corner of the screen, but no video window is seen. Now no TV stream cant be played on the iPad anymore, Even if airplay is turned off. In order to get the stream up again, the iPad must be rebooted first. Is this a known issue? Can it be worked around? Airplay is a bit essential as KODI also cannot succesfylly play TV streams on the appletv4.

Kai

Sendt fra min iPad

**Comment by zipleen** [comment]
Yes, tvhclient needs access to the web interface (that's why I asked if you could access the web interface through safari, if you can you should use the same credentials).

Airplay from the internal player will never work, because the Apple TV (in airplay mode) will require a video stream compatible with Apple's approved streams - DVB-* streams are normally not in that format and tvheadend would be required to transcode the stream to a format that the Apple TV understands.

I'm nearly finishing TvhClient for the Apple TV which will allow you to watch tv channels from tvheadend. If you want I can add you to the beta. Send me an email where I can send the invite to (do _not_ hit reply on this email, as it will be recorded in the github issue https://github.com/zipleen/tvheadend-iphone-client/issues/171)

**Comment by kmengvik** [comment]
Thanks, that would be great! How can I send you a private message with my e-mail?

**Comment by zipleen** [comment]
I don't think there's private messages here, send me an email to tvhclient@gmail.com

**Comment by kmengvik** [comment]
Ok,I sent it off now.

Cheers!
