### ISSUE TITLE
Unable to Fast Forward recordings on Apple TV

### ISSUE THREAD

**Issue by gazzer82** [zipleen/tvheadend-iphone-client#185]
So I have TvhClient running on my Apple TV, generally everything works as expected. But I am unable to fast forward through recordings, it works for about 20 seconds then the picture freezes and never returns. 

I am running tvheadend version 4.1-2336 on a Raspberry Pi 3 on Jessie. The recordings are stored on a symbology NAS via NFS. But I get the same issue when I was running tvheadend directly on my NAS. Everything is hard wired into the same network switch so I don't think there are networks issues here. 

Any ideas what might be causing this, or anything I could do to troubleshoot?

Thanks

Gareth

**Comment by zipleen** [comment]
Really old one, but this is probably due to MKV/TS recording profile and VLC. 

VLC does not do a good job of scrubbing with TS, but TS is required if you want to start watching recordings while they're recording. So you can switch to MKV to have scrubbing, but if the recording crashes you'll need to manually fix the MKV - and you also need to wait for the end of the recording for the MKV to be playable.
