### ISSUE TITLE
Transcoding seems not working

### ISSUE THREAD

**Issue by yamlfd** [zipleen/tvheadend-iphone-client#187]
I try to stream from my htpc with tvheadend to my iphone. Configured 288 resolution and the stream is nearly 10mbit/second. I tried webem and all others, but the bandwidth does not reduce. I think this is not realistic and looks more like the native ts stream from DVB-S2.

What am I doing wrong?

**Comment by zipleen** [comment]
the transcoding option only works for tvheadend 3.6 (an old version, latest ones are 4.xx)

Are you using version 3.6 ? if not, then those options mean nothing. I suggest you setup a new users in tvheadend, set (lock) that user with the profile that does transcoding and then configure that user in tvhclient. This will mean that the user will be locked to that transcoding setting by tvheadend. You can configure the server 2 times, one with the transcoding user and the other without it to easily swap between transcoded or not streams.

**Comment by yamlfd** [comment]
I'm on tvheadend 4.0.9

What is the plan about this exteme useful feature? Why has it broken in tvheadend and will it come back soon?

**Comment by zipleen** [comment]
It is not broken, that feature is only for 3.6 because it was the only way to do transcoding back then.

After tvheadend 3.9 (development for 4.xx), profiles were introduced. Profiles are not supported by tvhclient right now, hopefully in the near future they'll be supported, but the new user workaround is quite easy to do and works as expected

**Comment by zipleen** [comment]
Track https://github.com/zipleen/tvheadend-iphone-client/issues/160 for updates
