### ISSUE TITLE
Channel numbers in the UI

### ISSUE THREAD

**Issue by maurymarkowitz** [zipleen/tvheadend-iphone-client#188]
TVHC should support channel numbers separately from names. This would have a number of effects...

- sorting in the EPG should be by channel or name
- in the channel view, the name and channel should be on different lines in the icon.
- the user should have settings to show channel, name or both in the channel view. They should also be able to select whether the channel is on the top or bottom of the name.

**Comment by aleroot** [comment]
I think that channel number is really something to add, I would want to have the option to switch directly a channel by its number.
it should be enough to have a button that open up a numeric input keyboard so that it would be possible to input the channel number and switch directly from there. I think it should be implemented on all devices : iPad/iPhone and Apple TV.

**Comment by zipleen** [comment]
Added in 1.1.0
