### ISSUE TITLE
2.7.10 crashing

### ISSUE THREAD

**Issue by thosirl** [zipleen/tvheadend-iphone-client#195]
Hi,
Just updated to tvhclient 2.7.10 on both iPad and iPhone and it's crashing within about 10seconds of launching, regardless of any action and even when not doing anything . Both devices running iOS 10.2.1. Tvheadend server is 4.0.9-13

Any ideas?

Tom

**Comment by zipleen** [comment]
Yes
It seems the status screen could be using a lot of memory, probably because the fix allowed it to consume every single source.

Try creating a user, remove "admin" rights for it in tvheadend and use that user in TvhClient - if it doesn't crash anymore please let me know.

I'll be looking at this tomorrow and see if I can get a bug fix asap

**Comment by thosirl** [comment]
Ok, removing admin rights seems to work.

**Comment by zipleen** [comment]
@thosirl can I get access to a server that triggers that error? 
It can be for a few hours only, until I capture the network traffic that causes the crash to happen

**Comment by zipleen** [comment]
@thosirl still alive? Can I get access to a server that contains a lot of those services, i.e with admin rights? 

I'm trying to test a fix for this, but I have no servers which have a lot of services...

**Comment by zipleen** [comment]
This has been fixed in the new release, it will be released soon to the app store. https://github.com/zipleen/tvheadend-ios-lib/commit/6bd23b1111c6a8e59998ff66f5734bb4d4d0c958
