### ISSUE TITLE
User requires admin right due to status polling

### ISSUE THREAD

**Issue by jacotec** [zipleen/tvheadend-iphone-client#197]
I'm using TVH behind a SSH reverse proxy server to secure access. Using the great TVH app on our IDevices was resulting in being locked out when we are remotely by my OSSEC HIDS which is monitoring the proxy server.

The reason was multiple web server 4xx errors caused by the plugin. Digging deeper in the logs, I found these kind of requests:

```
109.44.2.61 - max_road [12/Apr/2017:21:52:56 +0200] "GET https://my.server.de/api/status/subscriptions HTTP/1.1" 401 199 "-" "TvhClient/676 (iPad; iOS 10.3.1; Scale/2.00)" "-" 0.000
109.44.2.61 - max_road [12/Apr/2017:21:52:56 +0200] "GET https://my.server.de/api/status/inputs HTTP/1.1" 401 199 "-" "TvhClient/676 (iPad; iOS 10.3.1; Scale/2.00)" "-" 0.000
```

These requests which the TVH client sends out do only work if the user has admin rights. As I don't want all of my users being admins, I have the choice of being flooded by 401 errors or giving all users admin rights.

Also I have the feeling that these unanswered requests causes trouble with the app at some point. Being not an admin, watching streams will crash after 2-3 channel changes unless TVH kills the dead stream by itself. Being admin as a user does not show any issues at all.

I'd highly appreciate if also non-admin users would be fully functional.

**Comment by zipleen** [comment]
Hi !

The 401 errors are not a big deal for tvheadend, apart from flooding the debug logs. The non-admin features are always queried, but if it fails nothing is broken as well (the status screen won't show anything). 

Channels, EPG and viewing tv is not affected by this.

Are you sure tvheadend crashes because a client is doing a lot of queries to the api endpoint that gives 401 ? That looks suspicious. 

I need to investigate further on how I would be able to stop this queries.

If you have any object-c expertise and can help, here's the start of the code that does all of this https://github.com/zipleen/tvheadend-ios-lib/blob/master/tvheadend-ios-lib/TVHServer.m

**Comment by zipleen** [comment]
I've added an option in each server to disable the options that require admin rights.

On each server, the last option asks "User has admin access" which you can set to off. Obviously this will disable the entire status screen (no data will be shown there).
