### ISSUE TITLE
Start of stream is delayed

### ISSUE THREAD

**Issue by kalle2000** [zipleen/tvheadend-iphone-client#206]
I am using tvhclient on a number of apple devices, e.g. Iphone, ipad ...

I recently installed tvhclient on the appletv4k and i am curious why the start of the stream takes a few seconds. Same with switching channels. On my kodi box with a tvh client switching channels is much faster.
Is it standard behaviour on the appletv or is there a way to speed it up?

Thx and regards
Dan

**Comment by zipleen** [comment]
that probably has to do with the vlc cache size you configured (or default one set) in the server config.

set a lower cache size for faster switching (with local lan connections this should be perfectly fine, with internet connections this is probably not good)

also, switching between channels on the apple tv (using the popup channel switcher) has an artificial 0.2sec of delay - this was due to vlc not behaving very well if we tried to swap the stream right away. I might re-test this value with the latest betas to check if this is still needed though =)

**Comment by MagicChocoRolls** [comment]
I encountered the same "problem". I found out that HTSP streaming (what Kodi uses) indeed is a bit faster than HTTP streaming, what the thvclient uses.
In my opinion, the delay with tvhclient is still usable :)

**Comment by kalle2000** [comment]
Reducing the cache did some improvement. After i changed the tvh dns name with the static (local) ip, switching is waaaay better now. No idea how much htsp instead of http pushes it further.  I am fine.

Thx for the help
