### ISSUE TITLE
No Subtitle on iPhone X with internal VLC

### ISSUE THREAD

**Issue by killercheung** [zipleen/tvheadend-iphone-client#208]
I would like to report subtitle cannot display on the iphone x with the internal VLC player
It seems only affect iPhone X,   I have no such problem on the iPad Pro / use external player (nPlayer) 
Both device running iOS 11.2 beta 3

**Comment by killercheung** [comment]
Thank you! Problem sloved!

Since I use tvhclient mainly for interlanced source, I thought I shouldn't turn on hardware decoding.

**Comment by zipleen** [comment]
You're correct, hardware decoding is _not_ used. But for some weird reason if the hardware decoding option is not enabled, subtitles don't work... Hence the ticket in vlckit :/ 

I didn't enable hardware decoding as a default option because there's some hiccups that occurred with it enabled - although again, they shouldn't have any difference because it's using software decoding, but it does! Oh well...

**Comment by zipleen** [comment]
This bug is now fixed, but only on the next release. Once https://code.videolan.org/videolan/VLCKit/issues/123 is fixed I'll be able to push the new version.
