### ISSUE TITLE
Deinterlace broken no ATV4K

### ISSUE THREAD

**Issue by salondigital** [zipleen/tvheadend-iphone-client#209]
Hi!

I'm a new user of an Apple TV 4K, I'm trying to use tvheadend app for tvos, but none of deinterlace options works correctly. On the other hand I installed MrMC and with option "Deinterlace" (Yadif) everything is working perfectly, so...what's wrong?

Thanks in advance!

**Comment by zipleen** [comment]
Hi!

I have an Apple TV 4K with an 4K TV and I can confirm that deinterlace is not broken on the app store stable version. I've tried with Off, Blend, Linear and Yadiff (2x) and I can clearly see the differences.

I've taken photos from my tv (and not screenshots) to clarify that this is indeed working.
My settings are:
- Apple TV 4K
- 4K 60Hz SDR
- TvhClient from the tvOS App Store (1.0.2)
- tvOS 11.2 beta (but I seem to remember that it worked just fine on the stable tvOS 11 stable versions as well)

No deinterlace:
![img_0217](https://user-images.githubusercontent.com/1225055/32979458-7f7b9cce-cc4d-11e7-9625-1e96c8670c5c.jpg)

Blend:
![img_0218](https://user-images.githubusercontent.com/1225055/32979466-98f5dc1e-cc4d-11e7-9e72-2d5e2afb1f78.jpg)

Bob:
![img_0219](https://user-images.githubusercontent.com/1225055/32979468-9e1c9250-cc4d-11e7-827b-b2151fbb44c1.jpg)

Linear:
![img_0220](https://user-images.githubusercontent.com/1225055/32979472-a1a55786-cc4d-11e7-929b-6d9af1e18ede.jpg)

Yadiff(2x):
![img_0221](https://user-images.githubusercontent.com/1225055/32979474-a3b8e45c-cc4d-11e7-8f7f-bd29a5448158.jpg)

I think it's fair to say that deinterlace is indeed working, if you select it in the settings screen it should work.
A lot of beta testers of TvhClient are also very picky about deinterlace and none have complained that it's not working (for the stable version in the app store).

However, I did fail to understand what does MrMC have anything to do with TvhClient. If you compared VLC then it would make perfect sense, but MrMC does not.

**Comment by salondigital** [comment]
Ok, maybe the problem is the 50 Hz (I'm living in Spain). You're correct, it's working, but it's jerky (not smooth, it's like a frame dropped every 1-2 seconds).

I can't understand why the same deinterlace option ("Deinterlace" = Yadif) in MrMC is perfectly smooth and not in TVHClient.

Thanks for your quickly reply!

**Comment by salondigital** [comment]
I tried also with 4K@60 and 1080@60 and same problem, It's like 35 fps or something like this, not smooth.

I recorded small video with TVHClient and MrMC, you can clearly see the difference, in TVHClient the video is jerky, not smooth. In MrMC is perfect (50 fps interleaced):

https://youtu.be/mvCJ2p2aEAo

Thanks again and amazing job, I really love the tvhclient interface and I want to stay with this app ;)

**Comment by zipleen** [comment]
MrMC and TvhClient use completely different codebases. 

TvhClient uses VLCKit, so you can compare TvhClient and VLC (they should be the same).

However the jerkiness that you are experiencing has nothing to do with deinterlacing. With deinterlacing on or off it's exactly the same issue.

Personally I don't notice it a lot and my sources are also all 25fps, but there's little I can do because it's all down to VLCKit and how it handles these cases.

**Comment by salondigital** [comment]
Yes, you're right. Same jerky image with VLC too.

Maybe if I can disable HW acceleration the problem disappears?

**Comment by zipleen** [comment]
There's no hardware acceleration in the VLCKit build in the app store =) 

I'm testing the latest VLCKit versions for the past 6 months, but the app is crashing too much to release a new version. 
Also, hardware decoding doesn't do anything for us broadcasting people because interlaced content cannot be decoded in hardware by iOS (i.e VideoToolBox does not support it and VLC falls back to software decoding). This is also why it's mostly useless to even try the internal iOS player, as most of the broadcasting is done interlaced and it will never decode that - see http://www.openradar.me/30669495 . 

If you want you can join the beta testers to test new builds - we're at http://chat.tvhclient.com , send me a private message with your email and I'll add you to testflight. Right now I haven't pushed any new version because it's still crashing too much while stopping a video.
