### ISSUE TITLE
Transparant Icon not visible

### ISSUE THREAD

**Issue by lxlngr** [zipleen/tvheadend-iphone-client#210]
Hi there. Love the app. But. 

I use this icon set: 

https://github.com/Stevie-v/srp.220x132.transparent-white-ziggo/find/master?q=

The thing is. I cannot see icon on the channel homescreen of tvh app but I do see icon at the program info screen. (After selecting channel—>program in top right corner)

Is this be fixable in any way?

Cheers. 

LX

**Comment by zipleen** [comment]
I don't think this is fixable by tvhclient, because you have white icons, with transparent backgrounds on a white background of iOS. White + White == you can't distinguish the background from the icon itself. 

Those icons only work on a black background. Add borders to the icons or add a background to the icons. There isn't much I can do =)
