### ISSUE TITLE
Feature Request: search also EPG description

### ISSUE THREAD

**Issue by duffy6** [zipleen/tvheadend-iphone-client#211]
Would it be possible to search not only within the title of EPG and also in the description?

Greetz
duffy6

**Comment by zipleen** [comment]
I already got a request for this, and technically there's no issue, it's just a flag that needs to be passed, but I'll explain what is the big problem around such a "simple request".

My issue is the change of behaviour from what has happened for the past 5 years - I'm struggling to understand how to implement this:
- for you, obviously you would say that you want to search the description
- what's the impact for other people, that for some reason that I do not know, only want to search the program names
- it would be nice to add this option to the search bar, but I've looked into that a couple of weeks back and refactoring just to get that option seems too much work
- adding a new option on settings will now bypass the threshold of the amount of settings that I'm cramming into 1 screen - which you can say "just make a folder and put those options in", but the issue is that the  settings code was not meant to handle this, it's pretty raw and doing this just means more and more work

I really don't know how I can measure the impact on other people. If I use the metric of "how many people have complained after I change this option to include description", then the reverse "how many people complained that want this option" is 2 over the entire population of the app - which means that users do not care about this option. It's not a good metric to use either way...

**Comment by duffy6** [comment]
I think it would be best to just add a new button (on the lower end of the screen) for „search“
And there you can add a button for search only title or search also description.

As long there are no other apps for this users will stay with the app but as soon as there is an other app available...

**Comment by zipleen** [comment]
> As long there are no other apps for this users will stay with the app but as soon as there is an other app available...

You know, that comment could be correct _if_ I made any money out of this app, but I don't. It's a free app that I develop on my own spare time. 

As for the option, I still need to think where to put this option because it does make sense to have it.

**Comment by zipleen** [comment]
Next version will default to always doing a search with full text.
