### ISSUE TITLE
Unable to record the current TV show

### ISSUE THREAD

**Issue by evilgoldfish** [zipleen/tvheadend-iphone-client#243]
I can't seem to add the currently playing show as a recording in the tvOS app. TvhClient will display a success message saying "Successfully added Recording" on the bottom right but no recording actually gets added to the TVHeadend web UI, nor the Recordings tab in the client. I know this is definitely something TVHeadend supports as I can click "Start Recording" in the Web UI and have this work. Any chance this will be fixed/added to the app?

Massive thanks by the way, this app works very well.

**Comment by evilgoldfish** [comment]
As an aside, it seems to _sort of_ work in the iOS client - I can start the recording once but if I cancel it and try to record again, the recording won't start.

**Comment by zipleen** [comment]
things can't sort of work and then not work for no apparent reason :p 

what is your exact tvheadend version? is your user able to do these actions?

I can guarantee that I have recordings working because this is the exact reason why I've built tvhclient and the action that I use it for. This might mean that it's something related to either the way you have your tvheadend configured, or your specific tvheadend version, so it would be nice if I could get access to your server to test this example and reproduce it on my environment.

**Comment by evilgoldfish** [comment]
Ended up fixing this, along with a whole slew of weird bugs, by not using the default admin user and creating a new client user with restricted privileges.
