### ISSUE TITLE
Encoded file is not listed in recording complete file

### ISSUE THREAD

**Issue by xswqaz** [zipleen/tvheadend-iphone-client#244]
I'm using apple tv app
mp4 file which I encoded recording completed file is not appeared in Recording list
Is it not possible?

I encoded ts file  to mp4 file which enable to play with iPhone

**Comment by zipleen** [comment]
I'm not really sure what you mean, can you give a more explicit example with the actions that you were doing and how you converted?

In a nutshell, go to the tvheadend http UI, if you can see it there in the recordings and click "download" and get the mp4 file, then tvhclient will work. If you can't and tvheadend does not know anything about the file, then it won't work because tvhclient will just have the data that tvheadend gives back.

**Comment by xswqaz** [comment]
I know what you mean
close it
