### ISSUE TITLE
HowTo

### ISSUE THREAD

**Issue by shila77** [zipleen/tvheadend-iphone-client#245]
Watched the video manual...

How should i get the following dialog from guide?
![Bildschirmfoto 2019-03-24 um 22 52 44](https://user-images.githubusercontent.com/25443033/54886592-e7ebff00-4e89-11e9-9eb6-712355e6fb0e.png)

Thanks in advance.

**Comment by zipleen** [comment]
for any epg entry that's not currently on going, you just hit the normal "select" button.

For the currently on going EPG entry, on version 1.0 it was just hitting select button. but there was a couple of people (including me) that forgot that clicking on the Play button it would automatically play. So I changed this behaviour to "if you hit select it will start playing". Unfortunately it means this screen does not exist anymore for the currently selected channel... 

I might change this back on the next version because it makes more sense how it was before (but discoverability that the play button starts the channel is hard to guess).

**Comment by shila77** [comment]
Hallo,

Thanks for answering.

Feature requests:

Providing more Info in Guide.
Not only show current event in channel also next.

Regards
Shila77

Luis Fernandes <notifications@github.com> schrieb am Mo. 25. März 2019 um
00:45:
