### ISSUE TITLE
Stutter playback on non tvOS paid version

### ISSUE THREAD

**Issue by lwis** [zipleen/tvheadend-iphone-client#247]
Lots of apps are now switching to mpv for video playback, I'm in the UK and currently unable to stream DVB-T2 smoothly on my ATV 4K using TvhClient, while I get smooth playback using Channels - I assume they're using a different video playback method such as mpv? 

I don't want to say goodbye to Tvheadend :(

**Comment by zipleen** [comment]
I've looked into the mpv library and it's completely different implementation - I actually didn't manage to compile it back then lol - you can read about it in https://gitter.im/zipleen/tvheadend-iphone-client?at=5bff55a3ced7003fe1a0e13f and around that date.

in a nutshell, changing from VLC to MPV would be a complete rewrite and also a complete removal of vlc because both libraries don't get along.

but on another note, why don't you have smooth playback? what started to happen? I'm also in the uk and DVB-T2 and my playback is always "smooth" (or at least works for me lol)

**Comment by lwis** [comment]
@zipleen Okay, thanks for getting back to me!

I've done some digging and it looks like Channels is also using libvlc with hw decoding and linear deinterlacing. 

I picked up an ATV 4K last week to replace a Pi 3, so I've been trying out tvh options, and your app fits the bill almost entirely. 

What settings are you using tvh side? I'm using using the 'pass' profile. Also interesting is that recording the same content on Channels and tvh gave me two very different file sizes (1.5GB on tvh, 2.1GB on Channels).

You've given me faith that this is likely a configuration issue on my end!

**Comment by lwis** [comment]
tvh;

```
Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
Stream #0:1[0x101](eng): Audio: aac_latm (LC) ([17][0][0][0] / 0x0011), 48000 Hz, stereo, fltp
```

Channels;

```
Stream #0:0[0x19c9]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
Stream #0:1[0x19ca](eng): Audio: aac_latm (LC) ([17][0][0][0] / 0x0011), 48000 Hz, stereo, fltp
```

**Comment by lwis** [comment]
I just tried playing a HD stream directly in the VLC app on the ATV, which works flawlessly.

**Comment by zipleen** [comment]
fixed on the next version.
