### ISSUE TITLE
The last update of VLC doesn’t work

### ISSUE THREAD

**Issue by Delurkdotcom** [zipleen/tvheadend-iphone-client#253]
Hi,

When I try to launch a tv channel on VLC from the « play » button, VLC starts but nothing happens.

It started since the last update of VLC : 3.2.0

On the other hand, the feed works if you copy the link on VLC.

**Comment by zipleen** [comment]
This means they might have changed the url format or layout - I'll need to have a look at it

**Comment by zipleen** [comment]
In the meantime you can use the internal player which is VLC anyway - out of curiosity,  any special reason why you're using the external VLC?

**Comment by Delurkdotcom** [comment]
Because performances are bad with the  internal VLC on iPad 4 (MD510FD/A)

**Comment by zipleen** [comment]
But not with the VLC app? Which settings do you use in VLC to make it work correctly? Maybe I can add the missing option to make it work with the internal VLC. 
I do have an iPad 3 that I can test with, what channel properties do you see the performance issues? SD with deinterlacing?

**Comment by Delurkdotcom** [comment]
VLC app works great with default settings unlike the internal app which display all channels with many freeze but sound is okay.

I use the default profile from tvheadend (pass). I watch channels in hd when it’s available.

**Comment by zipleen** [comment]
Mmmm, that doesn't make sense - the code for VLC and tvhclient in regard of playback is the same - if should work exactly the same on both. Even the default settings are the same.
There's really no difference - so either you have a very good reproducible error that I would very much like to fix, or you're thinking that it's slower when it probably isn't. I would need to test the same conditions and reproduce the problem.

I won't be able to fix the VLC issue for at least two weeks because I'm not near my dev computer, sorry! Once I'm back I'll try pushing a beta release ASAP .

**Comment by zipleen** [comment]
VLC 3.2.1 has been released and one of the changelogs is +· Fix opening media from other applications using x-callback-url

This probably means VLC works correctly again and it was their issue.

I would still like to fix your performance issue
