### ISSUE TITLE
HEVC support

### ISSUE THREAD

**Issue by eutampieri** [zipleen/tvheadend-iphone-client#257]
Hello, this evening I was trying the test HEVC stream for Italy, but it wasn’t playing on my iPad and on my Apple TV. This is strange because if I record the stream and I play it back through the in app player then it works. Here are the stream's details:

Index | PID | Type | Language | Details
-- | -- | -- | -- | --
  | 0x01f4 /   500 | PCR |   |  
  | 0x012c /   300 | PMT |   |  
1 | 0x01f4 /   500 | HEVC |   |

**Comment by zipleen** [comment]
Hey, more details are needed.

This is because hevc is supported, I've played around with 4k streams with test channels and they work.

There must be something funny happening if you can playback the file after recorded but you can't with the live stream. Try to playback the live stream with VLC and let me know if it works. If it also breaks then it could be a VLC bug / tvheadend issue for your stream!

**Comment by eutampieri** [comment]
So, I don’t know why but now it works. I’m sorry for wasting your time
